export const locations = [
  "Lagos",
  "Abuja",
  "Port Harcourt",
  "Ibadan",
  "Kano",
  "Enugu",
  "Benin City",
  "Kaduna",
  "Jos",
  "Abeokuta",
  "Ilorin",
  "Owerri",
  "Makurdi",
  "Akure",
  "Osogbo",
  "Uyo",
  "Calabar",
  "Warri",
  "Asaba",
  "Sokoto",
  "Maiduguri",
  "Yola",
  "Bauchi",
  "Minna",
  "Gombe",
  "Onitsha",
  "Awka",
  "Abakaliki",
  "Lokoja",
  "Katsina",
  "Zaria",
  "Eket",
  "Ado Ekiti",
  "Oshogbo",
  "Umuahia",
  "Jalingo",
  "Birnin Kebbi",
  "Gusau",
  "Damaturu",
  "Dutse",
];

export const services = [
  "Electrical",
  "Plumbing",
  "Carpentry",
  "Painting",
  "Masonry",
  "Tiling",
  "POP/False Ceiling",
  "Welding/Fabrication",
  "Generator Repair",
  "AC Repair",
  "Cleaning",
  "Laundry",
  "Hairdressing",
  "Tailoring",
  "Barbing",
  "Auto Mechanics",
  "Aluminum Works",
  "Furniture Making",
  "Upholstery",
  "Pest Control",
  "Satellite Installation",
  "Refrigerator Repair",
  "Gas Cooker Repair",
  "Door & Window Installation",
  "Iron Bending",
  "Roofing",
  "Block Moulding",
  "Landscaping",
  "Interlocking",
  "Screeding",
];

export const detailedServices = [
  {
    title: "Home Repairs",
    description: "Professional repairs for your home maintenance needs",
    icon: "🛠️",
    features: [
      "Plumbing repairs",
      "Electrical fixes",
      "Carpentry work",
      "Painting services",
      "Roof leakage repairs",
      "Door & window installation",
    ],
  },
  {
    title: "Renovations & Finishing",
    description:
      "Transform your space with our renovation and finishing services",
    icon: "🏗️",
    features: [
      "Masonry work",
      "Tiling installation",
      "POP/False ceiling fitting",
      "Screeding & wall finishing",
      "Flooring & interlocking",
      "Block moulding",
    ],
  },
  {
    title: "Mechanical & Technical",
    description:
      "Get expert mechanical and technical servicing for your machines and appliances",
    icon: "🔧",
    features: [
      "Auto mechanic services",
      "Generator repair & servicing",
      "AC installation & repairs",
      "Refrigerator & freezer repairs",
      "Gas cooker repairs",
    ],
  },
  {
    title: "Fabrication & Metal Works",
    description: "High-quality welding and metal fabrication services",
    icon: "⚙️",
    features: [
      "Welding and iron works",
      "Gate and fence fabrication",
      "Aluminum doors and windows",
      "Iron bending and installation",
    ],
  },
  {
    title: "Cleaning & Environmental",
    description: "Ensure your environment stays clean, fresh, and pest-free",
    icon: "🧼",
    features: [
      "Residential & office cleaning",
      "Deep cleaning services",
      "Laundry pickup & delivery",
      "Pest control & fumigation",
      "Landscaping and gardening",
    ],
  },
  {
    title: "Furniture & Interiors",
    description: "Beautiful, custom-built furniture and interior solutions",
    icon: "🪑",
    features: [
      "Furniture making & repairs",
      "Upholstery & re-upholstery",
      "Curtain & blind installation",
      "Interior décor support",
    ],
  },
  {
    title: "Beauty & Grooming",
    description: "Stay stylish with our mobile beauty and grooming experts",
    icon: "💇‍♀️",
    features: [
      "Hairdressing services",
      "Barbing for men and kids",
      "Tailoring & fashion design",
      "Mobile makeup & gele tying",
    ],
  },
  {
    title: "Smart Home & Electronics",
    description:
      "Installation and repairs for your electronics and smart systems",
    icon: "📡",
    features: [
      "Satellite dish installation",
      "TV wall mounting",
      "Home sound systems",
      "Basic CCTV installation",
    ],
  },
  {
    title: "Emergency Services",
    description: "24/7 emergency repair and rescue services for urgent needs",
    icon: "🚨",
    features: [
      "Burst pipe & plumbing leaks",
      "Power outage assistance",
      "Generator & AC breakdown",
      "Roof/storm damage repair",
    ],
  },
];
